name             'custom_apache'
maintainer       'Chef Software, Inc'
maintainer_email 'training@chef.io'
license          'Apache-2.0'
description      'Installs/Configures custom_apache'
long_description 'Installs/Configures custom_apache'
version          '0.1.0'
issues_url 'https://github.com/markachus/custom_apache/issues'
source_url 'https://github.com/markachus/custom_apache'
chef_version '>=' if respond_to?(:chef_version)
supports 'ubuntu'
